### ISSUE TITLE
Html is generated in the default location even if an output directory is specified 

### ISSUE THREAD

**Issue by dhillonks** [DerekJxy/My-First-SSG#4]
The readme as well as the help section in the tool gives the user an option to use `-o or --output`. So, if the user uses that and specifies a specific location, the tool should generate the web pages in that directory.

For instance, I tried running:
```
 node server.js -i .\Sherlock-Holmes-Selected-Stories\ -o "output_dir"
```
It should store the results in `output_dir`, however it still stores the results in the default `./dist`. It seems like `./dist` is hardcoded:
https://github.com/DerekJxy/My-First-SSG/blob/ae06d0282140a92dfe07463a9be1b29ac8d85d83/server.js#L30-L43

**Comment by DerekJxy** [comment]
_Hmm.._ yeah I set that place all output into a `./dist` folder __by default__. And I didn't make a feature for the `output path` which is an __optional feature so far__. But your idea is __good__, I __should make that feature as well__.  :+1:   :+1:
