### ISSUE TITLE
Unable to use files as input using -i

### ISSUE THREAD

**Issue by dhillonks** [DerekJxy/My-First-SSG#5]
As per the readme, `node server.js -i '.\Silver Blaze.txt'` should produce a `Silver Blaze.html` in `./dist`.

However, the tool fails to generate HTML if a file is used as input using `-i or --input`. The following error appears in console: 

![image](https://user-images.githubusercontent.com/52294825/133706418-5b34dc64-9c91-47cf-bc31-8b8527f9363b.png)

**Comment by DerekJxy** [comment]
This is __because__ I'm having the `Silver Blaze.txt'` and the `server.js` in the __same folder__. You should just use the command `node server.js -i 'Silver Blaze.txt'`
